[server]
port = 7842

[app]
start_position_x = 100
start_position_y = 100
size = large
show_timer = true

; Animations lors d'un reset (utilisation retombe à ~0%) : true / false
anim_pulse = true
anim_blink = true

